Document JS Options
kottenator/node-sass-watcher pull request #3
Opened 2018-01-30 09:11 UTC by soulofmischief

Had to dig into the module to find out how to pass options to the Watcher.

Hopefully this will save others some time.

2018-01-31 16:11 UTC, kottenator requested changes

2018-01-31 16:11 UTC, kottenator commented on README.md
> +* includePaths
Please, wrap with backticks.

2018-01-31 19:33 UTC, soulofmischief commented
Funny, I thought if I went with backticks you would tell me to make it a list.

Is this more what you wanted, or do you want me to copy over the descriptions as well?

2018-01-31 20:08 UTC, kottenator commented
Not exactly what I wanted :)

Sorry, I wasn't clear enough with my request: could you, please, make it _as a list_ but _each keyword in backticks_?

Like:

```md
* `one`
* `two`
* `three`
```

2018-02-01 01:49 UTC, soulofmischief commented
Haha, of course. The dark deed you've requested is done, sir.

2018-02-01 02:03 UTC, kottenator approved these changes

2018-02-01 02:03 UTC, merged